# Generated by Django 2.2.9 on 2021-07-03 17:56

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('C', 'C'), ('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('Django', 'Django'), ('Laravel', 'Laravel'), ('GO', 'GO')], default='software', max_length=20, verbose_name='زبان برنامه نویسی')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('cat', 'اتوکد'), ('photoshop', 'فتوشاپ'), ('corel', 'کرل'), ('indesign', 'ایندیزاین'), ('catia', 'کتیا')], default='software', max_length=20, verbose_name='نرم افزارهای تخصصی')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, max_length=255, null=True, upload_to=accounts.models.get_avatar_directory_path, verbose_name='Avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_supermanager', models.BooleanField(default=False, verbose_name='مدیر کل؟')),
                ('is_centermanager', models.BooleanField(default=False, verbose_name='مدیر مرکز؟')),
                ('is_projectmanager', models.BooleanField(default=False, verbose_name='مدیر پروژه؟')),
                ('is_employee', models.BooleanField(default=True, verbose_name='عضو پروژه؟')),
                ('mobile_number', models.CharField(max_length=11, unique=True, verbose_name='تلفن همراه')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='تلفن ثابت')),
                ('address', models.TextField(blank=True, default='', verbose_name='نشانی')),
                ('sex', models.CharField(blank=True, choices=[('man', 'مرد'), ('woman', 'زن')], default='man', max_length=20, verbose_name='جنسیت')),
                ('degree', models.CharField(blank=True, choices=[('diploma', 'دیپلم'), ('bachelor', 'کارشناسی'), ('master', 'ارشد'), ('phd', 'دکتری')], default='bachelor', max_length=20, verbose_name='مدرک')),
                ('measure', models.CharField(blank=True, choices=[('software', 'نرم افزار'), ('electronic', 'الکترونیک'), ('mechanic', 'مکانیک'), ('control', 'کنترل'), ('civil', 'عمران')], default='software', max_length=20, verbose_name='رشته')),
                ('university', models.CharField(blank=True, choices=[('Sharif', 'دانشگاه صنعتی شریف'), ('Tehran', 'دانشگاه تهران'), ('Elmos', 'دانشگاه علم و صنعت ایران'), ('Amirkabir', 'دانشگاه صنعتی امیرکبیر'), ('Beheshti', 'دانشگاه شهید بهشتی'), ('Public', 'دانشگاه سراسری'), ('Azad', 'دانشگاه آزاد'), ('Pyam', 'دانشگاه پیام نور'), ('Privte', 'دانشگاه غیر انتفاعی')], default='Public', max_length=20, verbose_name='دانشگاه')),
                ('ohter_abilities', models.TextField(blank=True, default='', verbose_name='سایر توانایی ها')),
                ('resume', models.FileField(blank=True, max_length=255, null=True, upload_to=accounts.models.get_resume_directory_path, verbose_name='رزومه')),
                ('langs', models.ManyToManyField(blank=True, to='accounts.Lang', verbose_name='زبان های برنامه نویسی')),
                ('softwares', models.ManyToManyField(blank=True, to='accounts.Software', verbose_name='نرم افزارهای مسلط')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
