# Generated by Django 2.2.9 on 2021-08-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('super', 'مدیریت کل'), ('center', 'مدیریت مرکز'), ('center_financial', 'مدیریت مالی مرکز'), ('project_pack', 'مدیریت دسته پروژه'), ('project_pack_monitoring', 'نظارت دسته پروژه'), ('project', 'مدیریت پروژه'), ('project_monitoring', 'نظارت پروژه')], default='employee', max_length=20, verbose_name='کد')),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='ohter_abilities',
            new_name='other_abilities',
        ),
        migrations.AlterField(
            model_name='lang',
            name='name',
            field=models.CharField(choices=[('C', 'C'), ('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('Django', 'Django'), ('Laravel', 'Laravel'), ('GO', 'GO')], default='Python', max_length=20, verbose_name='زبان برنامه نویسی'),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(choices=[('cat', 'اتوکد'), ('photoshop', 'فتوشاپ'), ('corel', 'کرل'), ('indesign', 'ایندیزاین'), ('catia', 'کتیا')], default='photoshop', max_length=20, verbose_name='نرم افزارهای تخصصی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='accounts.Permission', verbose_name='دسترسی ها'),
        ),
    ]
