# Generated by Django 2.2.9 on 2021-08-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210823_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(choices=[('super', 'مدیریت کل'), ('center', 'مدیریت مرکز'), ('center_financial', 'مدیریت مالی مرکز'), ('project_pack', 'مدیریت دسته پروژه'), ('project_pack_monitoring', 'نظارت دسته پروژه'), ('project', 'مدیریت پروژه'), ('project_monitoring', 'نظارت پروژه')], default='employee', max_length=30, verbose_name='کد'),
        ),
    ]
