# Generated by Django 2.2.9 on 2021-08-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210823_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_centermanager',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_projectmanager',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_supermanager',
        ),
    ]
