# Generated by Django 2.2.13 on 2021-10-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210826_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(choices=[('users', 'مدیریت کاربران'), ('centers', 'مدیریت مراکز'), ('projectpacks', 'مدیریت دسته پروژه ها'), ('projects', 'مدیریت پروژه ها'), ('equipments', 'مدیریت تجهیزات'), ('transactions', 'مدیریت تراکنش ها'), ('center', 'مدیریت مرکز'), ('user', 'مدیریت کاربران مرکز'), ('equipment', 'مدیریت تجهیزات مرکز'), ('transaction', 'مدیریت تراکنش های مرکز'), ('projectpack', 'مدیریت دسته پروژه های مرکز'), ('projectpack_monitoring', 'کارشناس کنترل پروژه های مرکز'), ('project', 'پیمانکار پروژه های مرکز'), ('project_monitoring', 'نظارت پروژه های مرکز')], max_length=30, verbose_name='کد'),
        ),
    ]
