# Generated by Django 2.2.9 on 2021-08-26 11:13

from django.db import migrations, models
import django.db.models.deletion
import transactions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0006_auto_20210826_1113'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=transactions.models.get_transaction_attachment_directory_path, verbose_name='فایل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(choices=[('prepayment', 'پیش پرداخت'), ('installment', 'قسط'), ('paragraph', 'بند')], max_length=20, verbose_name='نوع')),
                ('value', models.IntegerField(default=0, verbose_name='مبلغ تراکنش')),
                ('sequence_number', models.IntegerField(default=0, verbose_name='شماره توالی تراکنش')),
                ('due_date', models.DateTimeField(verbose_name='موعد پرداخت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت شده')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('attachments', models.ManyToManyField(blank=True, to='transactions.TransactionAttachment', verbose_name='فایل ها')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_transactions.transaction_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='TaskTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.Transaction')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='centers.Task', verbose_name='فعالیت')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='ProjectTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.Transaction')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='centers.Project', verbose_name='پروژه')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='ProjectPackTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.Transaction')),
                ('project_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='centers.ProjectPack', verbose_name='دسته پروژه')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('transactions.transaction',),
        ),
    ]
