# Generated by Django 2.2.9 on 2021-08-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tittle',
            field=models.CharField(choices=[('prepayment', 'پیش پرداخت'), ('instalment', 'قسط'), ('paragraph', 'بند')], max_length=20, verbose_name='نوع'),
        ),
    ]
