# Generated by Django 2.2.13 on 2021-09-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20210917_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpacktransaction',
            name='due_progress',
        ),
        migrations.AddField(
            model_name='projecttransaction',
            name='due_progress',
            field=models.IntegerField(default=0, verbose_name='موعد وزنی پرداخت'),
        ),
    ]
