# Generated by Django 2.2.9 on 2021-07-03 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('type', models.CharField(choices=[('car', 'ماشین'), ('pc', 'رایانه'), ('laptop', 'رایانه همراه'), ('tablet', 'تبلت'), ('mobile', 'تلفن همراه')], default='laptop', max_length=20, verbose_name='نوع')),
                ('is_rented', models.BooleanField(default=False, verbose_name='اجاره؟')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='centers.Center', verbose_name='مرکز')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('at', models.DateTimeField(verbose_name='شروع قرارداد اجاره')),
                ('to', models.DateTimeField(verbose_name='ددلاین قرارداد اجاره')),
                ('payment', models.FloatField(default=0, verbose_name='مبلغ قرارداد اجاره')),
                ('paid', models.FloatField(default=0, verbose_name='مبلغ پرداخت شده')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خاتمه قرارداد')),
                ('is_reservation', models.BooleanField(default=True, verbose_name='فرآیند رزرو؟')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Profile', verbose_name='اجاره کننده')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='centers.Center', verbose_name='مرکز')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipments.Equipment', verbose_name='تجهیزات')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='centers.Project', verbose_name='پروژه')),
            ],
        ),
    ]
