# Generated by Django 2.2.13 on 2022-08-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_auto_20210821_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='base_prie',
            field=models.FloatField(default=0, verbose_name='هزینه( نفر ساعت)'),
        ),
        migrations.AddField(
            model_name='rent',
            name='reserve_for',
            field=models.IntegerField(default=1, verbose_name='اچاره به ازای نفر'),
        ),
    ]
