# Generated by Django 2.2.13 on 2022-08-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_auto_20220818_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='base_prie',
            new_name='base_price',
        ),
    ]
