# Generated by Django 2.2.9 on 2021-07-03 17:56

import centers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('employees', models.ManyToManyField(blank=True, to='accounts.Profile', verbose_name='اعضای مرکز')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='center_manager', to='accounts.Profile', verbose_name='مدیر مرکز')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع قرارداد')),
                ('to_be_finished', models.DateTimeField(verbose_name='سررسید قرارداد')),
                ('payment', models.IntegerField(verbose_name='مبلغ قرارداد')),
                ('paid', models.IntegerField(default=0, verbose_name='مبلغ پرداخت شده')),
                ('progress', models.IntegerField(default=0, verbose_name='درصد پیشرفت وزنی')),
                ('weightless_progress', models.IntegerField(default=0, verbose_name='درصد پیشرفت')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خاتمه قرارداد')),
                ('status', models.CharField(choices=[('to_do', 'جهت انجام'), ('inprogress', 'در حال انجام'), ('completed', 'انجام شده'), ('verified', 'تایید شده')], default='to_do', max_length=20, verbose_name='وضعیت')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='centers.Center', verbose_name='مرکز')),
                ('employees', models.ManyToManyField(blank=True, to='accounts.Profile', verbose_name='اعضای پروژه')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_manager', to='accounts.Profile', verbose_name='مدیر پروژه')),
            ],
        ),
        migrations.CreateModel(
            name='SubTaskAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=centers.models.get_subtask_attachment_directory_path, verbose_name='فایل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=centers.models.get_task_attachment_directory_path, verbose_name='فایل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع قرارداد')),
                ('to_be_finished', models.DateTimeField(blank=True, null=True, verbose_name='سررسید قرارداد')),
                ('payment', models.IntegerField(default=0, verbose_name='مبلغ قرارداد')),
                ('paid', models.IntegerField(default=0, verbose_name='مبلغ پرداخت شده')),
                ('weight', models.IntegerField(default=1, verbose_name='وزن')),
                ('progress', models.IntegerField(default=0, verbose_name='درصد پیشرفت')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خاتمه قرارداد')),
                ('status', models.CharField(choices=[('to_do', 'جهت انجام'), ('inprogress', 'در حال انجام'), ('completed', 'انجام شده'), ('verified', 'تایید شده')], default='to_do', max_length=20, verbose_name='وضعیت')),
                ('attachments', models.ManyToManyField(blank=True, to='centers.TaskAttachment', verbose_name='فایل ها')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_employee', to='accounts.Profile', verbose_name='کارمند')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='centers.Project', verbose_name='پروژه')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع قرارداد')),
                ('to_be_finished', models.DateTimeField(blank=True, null=True, verbose_name='سررسید قرارداد')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خاتمه قرارداد')),
                ('status', models.CharField(choices=[('to_do', 'جهت انجام'), ('inprogress', 'در حال انجام'), ('completed', 'انجام شده'), ('verified', 'تایید شده')], default='to_do', max_length=20, verbose_name='وضعیت')),
                ('attachments', models.ManyToManyField(blank=True, to='centers.SubTaskAttachment', verbose_name='فایل ها')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subtask_employee', to='accounts.Profile', verbose_name='مسئول فعالیت')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='centers.Task', verbose_name='فعالیت')),
            ],
        ),
    ]
