# Generated by Django 2.2.9 on 2021-08-21 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='monitoring_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_monitoring_manager', to='accounts.Profile', verbose_name='ناظر پروژه'),
        ),
    ]
