# Generated by Django 2.2.9 on 2021-08-21 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_project_monitoring_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='monitoring_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='project_monitoring_manager', to='accounts.Profile', verbose_name='ناظر پروژه'),
            preserve_default=False,
        ),
    ]
