# Generated by Django 2.2.9 on 2021-08-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_projectpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='centers.ProjectPack', verbose_name='پک پروژه'),
        ),
    ]
