# Generated by Django 2.2.9 on 2021-08-26 11:13

import centers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0005_project_project_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=centers.models.get_project_attachment_directory_path, verbose_name='فایل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPackAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=centers.models.get_projectpack_attachment_directory_path, verbose_name='فایل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='project_pack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='centers.ProjectPack', verbose_name='پک پروژه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='centers.ProjectAttachment', verbose_name='فایل ها'),
        ),
        migrations.AddField(
            model_name='projectpack',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='centers.ProjectPackAttachment', verbose_name='فایل ها'),
        ),
    ]
