# Generated by Django 2.2.9 on 2021-08-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0006_auto_20210826_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='programmed_progress',
            field=models.IntegerField(default=0, verbose_name='درصد پیشرفت برنامه ای'),
        ),
    ]
