# Generated by Django 2.2.9 on 2021-08-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0007_project_programmed_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='programmed_progress',
        ),
    ]
