# Generated by Django 2.2.9 on 2021-08-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0008_remove_project_programmed_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_financial_statement',
            field=models.BooleanField(default=False, verbose_name='صورت مالی ایجاد شده؟'),
        ),
        migrations.AddField(
            model_name='projectpack',
            name='created_financial_statement',
            field=models.BooleanField(default=False, verbose_name='صورت مالی ایجاد شده؟'),
        ),
    ]
