# Generated by Django 2.2.9 on 2021-08-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0009_auto_20210827_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='usable_fund',
            field=models.IntegerField(default=0, verbose_name='مبلغ قابل استفاده جهت تسویه تسک'),
        ),
        migrations.AddField(
            model_name='projectpack',
            name='usable_fund',
            field=models.IntegerField(default=0, verbose_name='مبلغ قابل استفاده جهت تسویه پروژه'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_financial_statement',
            field=models.BooleanField(default=False, verbose_name='صورت مالی ایجاد شده؟'),
        ),
    ]
