# Generated by Django 2.2.9 on 2021-08-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0011_auto_20210828_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='project_employees', to='accounts.Profile', verbose_name='اعضای پروژه'),
        ),
    ]
