# Generated by Django 2.2.9 on 2021-09-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0012_auto_20210830_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time_supplement_form_uploaded',
            field=models.BooleanField(default=False, verbose_name='فرم متمم زمانی بارگذاری شده؟'),
        ),
        migrations.AddField(
            model_name='projectpack',
            name='time_supplement_form_uploaded',
            field=models.BooleanField(default=False, verbose_name='فرم متمم زمانی بارگذاری شده؟'),
        ),
    ]
