# Generated by Django 2.2.13 on 2022-03-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0014_auto_20220215_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='time_supplement_form_uploaded',
        ),
        migrations.RemoveField(
            model_name='project',
            name='time_supplemented',
        ),
        migrations.RemoveField(
            model_name='projectpack',
            name='time_supplement_form_uploaded',
        ),
        migrations.RemoveField(
            model_name='projectpack',
            name='time_supplemented',
        ),
    ]
