# Generated by Django 2.2.13 on 2022-03-11 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0015_auto_20220311_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpack',
            name='to_be_started',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='شروع قرارداد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectpack',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='شروع واقعی قرارداد'),
        ),
    ]
